displayName: Appmixer Webhook Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/traefik/webhook

summary: 'Parse and add FlowId and TriggerId Request Headers'

testData:
  headers:
    X-Flow-Id: flowId
    X-Trigger-Id: triggerId
  ipDepth: 0
